import streamlit as st
import json
from tools.analytics import get_analytics_summary
from tools.ticket import get_all_tickets
from tools.performance import get_performance_summary, load_performance_logs
from database.pg_client import check_connection_status
from database.schema import get_table_counts


def render_analytics_dashboard():
    """Render 📊 Customer Support Analytics & Performance APM Dashboard."""
    st.title("📊 Customer Support Analytics & APM Performance")
    st.caption("Real-time operational KPIs, resolution metrics, customer insights, revenue statistics, APM latency telemetry, and database infrastructure.")

    summary = get_analytics_summary()
    kpis = summary["kpis"]
    ticket_stats = summary["tickets"]
    customer_stats = summary["customers"]
    order_stats = summary["orders"]

    # --- Top KPI Executive Cards ---
    col1, col2, col3, col4, col5 = st.columns(5)
    col1.metric("🎫 Total Tickets", kpis["total_tickets"])
    col2.metric("🎯 Resolution Rate", f"{kpis['resolution_rate']}%", delta="Target > 90%")
    col3.metric("🚨 Open Escalations", kpis["open_tickets"], delta="Requires Action" if kpis["open_tickets"] > 0 else "Clear", delta_color="inverse")
    col4.metric("👥 Total Customers", kpis["total_customers"])
    col5.metric("💰 Total Revenue", f"₹{kpis['total_revenue']:,}")

    st.divider()

    # --- Analytics Tabs ---
    atab1, atab2, atab3, atab4, atab5 = st.tabs([
        "📈 Support Ticket Insights",
        "👥 Customer Base & Tiers",
        "📦 Order & Revenue Analytics",
        "⚡ Performance APM & Telemetry",
        "🐘 PostgreSQL & Vector Telemetry",
    ])

    # ---------------------------------------------------------------------------
    # Tab 1: Support Ticket Insights
    # ---------------------------------------------------------------------------
    with atab1:
        st.subheader("📈 Support Ticket Volume & Categories")

        tcol1, tcol2 = st.columns(2)

        with tcol1:
            st.markdown("#### 🎫 Tickets by Status")
            status_data = ticket_stats["by_status"]
            st.bar_chart(status_data, color="#6366f1")

        with tcol2:
            st.markdown("#### 🔥 Tickets by Priority Level")
            priority_data = ticket_stats["by_priority"]
            st.bar_chart(priority_data, color="#ec4899")

        st.markdown("#### 🏷️ Ticket Category Breakdown")
        category_data = ticket_stats["by_category"]
        st.bar_chart(category_data, color="#10b981")

    # ---------------------------------------------------------------------------
    # Tab 2: Customer Base & Tiers
    # ---------------------------------------------------------------------------
    with atab2:
        st.subheader("👥 Customer Membership, Language & Geographic Distribution")

        ccol1, ccol2, ccol3 = st.columns(3)

        with ccol1:
            st.markdown("#### 🏆 Customer Membership Tiers")
            membership_data = customer_stats["by_membership"]
            st.bar_chart(membership_data, color="#f59e0b")

        with ccol2:
            st.markdown("#### 📍 Top Customer Cities")
            city_data = customer_stats["by_city"]
            st.bar_chart(city_data, color="#3b82f6")

        with ccol3:
            st.markdown("#### 🌐 Preferred Languages")
            lang_data = customer_stats.get("by_language", {"English": 3, "Hindi": 2})
            st.bar_chart(lang_data, color="#10b981")

    # ---------------------------------------------------------------------------
    # Tab 3: Order & Revenue Analytics
    # ---------------------------------------------------------------------------
    with atab3:
        st.subheader("📦 Order Fulfillment & Revenue Metrics")

        ocol1, ocol2 = st.columns(2)

        with ocol1:
            st.markdown("#### 🚚 Order Fulfillment Statuses")
            st.bar_chart(order_stats["by_status"], color="#8b5cf6")

        with ocol2:
            st.markdown("#### 💳 Payment Method Distribution")
            st.bar_chart(order_stats["by_payment_method"], color="#06b6d4")

        st.markdown("#### 💰 Revenue Generated by Category (₹)")
        st.bar_chart(order_stats["revenue_by_category"], color="#10b981")

    # ---------------------------------------------------------------------------
    # Tab 4: Performance APM & Telemetry
    # ---------------------------------------------------------------------------
    with atab4:
        st.subheader("⚡ Agent Performance APM & Latency Telemetry")
        st.caption("Live latency profiling, node bottleneck tracking, token consumption, and APM execution logs.")

        perf_summary = get_performance_summary()

        p1, p2, p3, p4, p5 = st.columns(5)
        p1.metric("⚡ Avg Latency", f"{perf_summary['avg_latency_ms']} ms")
        p2.metric("⏱️ P95 Latency", f"{perf_summary['p95_latency_ms']} ms")
        p3.metric("🧠 Total Tokens", f"{perf_summary['total_tokens']:,}")
        p4.metric("📊 Avg Tokens / Run", perf_summary['avg_tokens_per_run'])
        p5.metric("✅ Success Rate", f"{perf_summary['success_rate']}%")

        st.divider()

        ptcol1, ptcol2 = st.columns(2)

        with ptcol1:
            st.markdown("#### ⏳ Average Latency per LangGraph Agent Node (ms)")
            st.bar_chart(perf_summary["node_avg_latencies"], color="#a855f7")

        with ptcol2:
            st.markdown("#### 🎯 Latency by Intent Category (ms)")
            st.bar_chart(perf_summary["intent_avg_latencies"], color="#ec4899")

        st.divider()

        st.markdown("#### 📜 Recent Execution Telemetry Traces")
        recent_logs = perf_summary.get("logs", [])
        recent_logs.reverse()

        for trace in recent_logs[:10]:
            t_id = trace.get("trace_id")
            user_id = trace.get("user_id")
            intent = trace.get("intent")
            total_lat = trace.get("total_latency_ms")
            p_tok = trace.get("prompt_tokens", 0)
            c_tok = trace.get("completion_tokens", 0)
            t_stamp = trace.get("timestamp", "")[:19].replace("T", " ")

            with st.expander(f"⚡ Trace `{t_id}` | User: `{user_id}` | Intent: {intent} | Latency: `{total_lat} ms`"):
                t_col1, t_col2 = st.columns(2)
                with t_col1:
                    st.markdown(f"**Timestamp:** `{t_stamp}`")
                    st.markdown(f"**Prompt Tokens:** `{p_tok}` | **Completion Tokens:** `{c_tok}`")
                    st.markdown(f"**Status:** `{trace.get('status')}`")
                with t_col2:
                    st.markdown("**Node Execution Breakdown (ms):**")
                    for n_name, n_lat in trace.get("node_latencies", {}).items():
                        st.caption(f"• `{n_name}`: {n_lat} ms")

    # ---------------------------------------------------------------------------
    # Tab 5: PostgreSQL & Vector Telemetry
    # ---------------------------------------------------------------------------
    with atab5:
        st.subheader("🐘 PostgreSQL Database & Vector DB Telemetry")

        db_status = check_connection_status()

        dbcol1, dbcol2 = st.columns(2)
        with dbcol1:
            st.markdown("#### 🔌 Database Connection Engine")
            st.info(f"**Active Mode:** {db_status['mode']}\n\n**Connection URL:** `{db_status['connection_url']}`")

        with dbcol2:
            st.markdown("#### 📦 Relational & Vector Record Volumes")
            counts = get_table_counts()
            if counts:
                st.bar_chart(counts, color="#3b82f6")
            else:
                st.info("PostgreSQL Fallback Mode (No active DB connection).")

    st.divider()

    # --- Data Export Section ---
    st.subheader("📥 Export Support & APM Reports")
    dcol1, dcol2 = st.columns(2)

    with dcol1:
        tickets = get_all_tickets()
        if tickets:
            import io
            import csv
            output = io.StringIO()
            writer = csv.DictWriter(output, fieldnames=tickets[0].keys())
            writer.writeheader()
            writer.writerows(tickets)
            csv_data = output.getvalue()

            st.download_button(
                label="📥 Download Support Tickets CSV Report",
                data=csv_data,
                file_name="support_tickets_report.csv",
                mime="text/csv",
                use_container_width=True,
            )

    with dcol2:
        analytics_json = json.dumps({
            "analytics_summary": summary,
            "performance_summary": get_performance_summary(),
            "database_status": check_connection_status()
        }, indent=4)
        st.download_button(
            label="📥 Download Full Analytics & APM Summary (JSON)",
            data=analytics_json,
            file_name="analytics_apm_summary.json",
            mime="application/json",
            use_container_width=True,
        )
